# checkpoint 间隔时间
checkpointInterval: 3000

# kafka 地址
kafkaBootstrapServers: kafka:9092
# kafka 数据源配置
kafkaSourceTopics: test
kafkaConsumeGroupIp: es-sink-group-003
kafkaSourceName: Kafka Source
esServer: es
esClusterName: es
kafkaSourceId: kafka-source
mainStreamName: dataSinkToElasticSearch
orcUrl: http://IP:PORT/url
aiUrl: http://IP:PORT/ai/recpeople
contentUrl: http://IP:PORT/url
gofastdfs: 192.168.15.10:10001
hdfs: 192.168.15.10:8020
# 字段名
fields: test.a1