# checkpoint 间隔时间
checkpointInterval: 3000

# kafka 地址
kafkaBootstrapServers: kafka:9092
# kafka 数据源配置
kafkaSourceTopics: test
kafkaConsumeGroupIp: es-sink-group-003
kafkaSourceName: Kafka Source
esServer: es
esClusterName: es
kafkaSourceId: kafka-source
mainStreamName: dataSinkToElasticSearch
# 字段名
fields: test.a1